# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-05-02T00:28:11+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class IsFluffyRequest(BaseModel):
    pet_type: str = Field(..., description='The type of Pet', example='cat')


class IsFluffyResponse(BaseModel):
    is_fluffy: bool
